version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    labels: ["dependencies", "ci"]
    assignees: ["techouse"]
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:30"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    labels: ["dependencies", "gradle"]
    assignees: ["techouse"]
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin:*"
      kotest:
        patterns:
          - "io.kotest:*"
      android-gradle:
        patterns:
          - "com.android.tools.build:gradle"
          - "com.android.tools:*"
      gradle-wrapper:
        patterns:
          - "gradle"
          - "gradle-wrapper"
