name: Docs

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Set up Gradle caching
        uses: gradle/actions/setup-gradle@v4
      - name: Build Dokka HTML (qs-kotlin)
        run: ./gradlew :qs-kotlin:dokkaHtml --stacktrace
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: qs-kotlin/build/dokka/html
          force_orphan: true
