name: Publish to Maven Central

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
  publish:
    needs: test
    name: Publish (Maven Central)
    runs-on: ubuntu-latest
    environment: maven
    permissions:
      contents: read

    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Show Java and Gradle versions
        run: |
          java -version
          ./gradlew --version

      - name: Publish to Sonatype (staging) and release
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace
